/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FlagTypeDto } from '../../models/flag-type-dto';

export interface AdminFlagsGet$Plain$Params {
}

export function adminFlagsGet$Plain(http: HttpClient, rootUrl: string, params?: AdminFlagsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FlagTypeDto>>> {
  const rb = new RequestBuilder(rootUrl, adminFlagsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FlagTypeDto>>;
    })
  );
}

adminFlagsGet$Plain.PATH = '/admin/flags';
