/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { accountForgotPasswordPost } from '../fn/account/account-forgot-password-post';
import { AccountForgotPasswordPost$Params } from '../fn/account/account-forgot-password-post';
import { accountLogoutPost } from '../fn/account/account-logout-post';
import { AccountLogoutPost$Params } from '../fn/account/account-logout-post';
import { accountRegisterPost } from '../fn/account/account-register-post';
import { AccountRegisterPost$Params } from '../fn/account/account-register-post';
import { accountResetPasswordPost } from '../fn/account/account-reset-password-post';
import { AccountResetPasswordPost$Params } from '../fn/account/account-reset-password-post';
import { accountValidateUserPost } from '../fn/account/account-validate-user-post';
import { AccountValidateUserPost$Params } from '../fn/account/account-validate-user-post';

@Injectable({ providedIn: 'root' })
export class AccountService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `accountRegisterPost()` */
  static readonly AccountRegisterPostPath = '/account/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `accountRegisterPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  accountRegisterPost$Response(params?: AccountRegisterPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return accountRegisterPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `accountRegisterPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  accountRegisterPost(params?: AccountRegisterPost$Params, context?: HttpContext): Observable<void> {
    return this.accountRegisterPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `accountValidateUserPost()` */
  static readonly AccountValidateUserPostPath = '/account/validate-user';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `accountValidateUserPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  accountValidateUserPost$Response(params?: AccountValidateUserPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return accountValidateUserPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `accountValidateUserPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  accountValidateUserPost(params?: AccountValidateUserPost$Params, context?: HttpContext): Observable<void> {
    return this.accountValidateUserPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `accountLogoutPost()` */
  static readonly AccountLogoutPostPath = '/account/logout';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `accountLogoutPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  accountLogoutPost$Response(params?: AccountLogoutPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return accountLogoutPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `accountLogoutPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  accountLogoutPost(params?: AccountLogoutPost$Params, context?: HttpContext): Observable<void> {
    return this.accountLogoutPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `accountForgotPasswordPost()` */
  static readonly AccountForgotPasswordPostPath = '/account/forgot-password';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `accountForgotPasswordPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  accountForgotPasswordPost$Response(params?: AccountForgotPasswordPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return accountForgotPasswordPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `accountForgotPasswordPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  accountForgotPasswordPost(params?: AccountForgotPasswordPost$Params, context?: HttpContext): Observable<void> {
    return this.accountForgotPasswordPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `accountResetPasswordPost()` */
  static readonly AccountResetPasswordPostPath = '/account/reset-password';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `accountResetPasswordPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  accountResetPasswordPost$Response(params?: AccountResetPasswordPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return accountResetPasswordPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `accountResetPasswordPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  accountResetPasswordPost(params?: AccountResetPasswordPost$Params, context?: HttpContext): Observable<void> {
    return this.accountResetPasswordPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
