/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DirectoryCreatedResponse } from '../models/directory-created-response';
import { DirectoryDetailDto } from '../models/directory-detail-dto';
import { DirectoryTreeDto } from '../models/directory-tree-dto';
import { ItemWithNameDto } from '../models/item-with-name-dto';
import { learningDirectoriesFileFileIdDelete$Json } from '../fn/learning/learning-directories-file-file-id-delete-json';
import { LearningDirectoriesFileFileIdDelete$Json$Params } from '../fn/learning/learning-directories-file-file-id-delete-json';
import { learningDirectoriesFileFileIdDelete$Plain } from '../fn/learning/learning-directories-file-file-id-delete-plain';
import { LearningDirectoriesFileFileIdDelete$Plain$Params } from '../fn/learning/learning-directories-file-file-id-delete-plain';
import { learningDirectoriesNewPost$Json } from '../fn/learning/learning-directories-new-post-json';
import { LearningDirectoriesNewPost$Json$Params } from '../fn/learning/learning-directories-new-post-json';
import { learningDirectoriesNewPost$Plain } from '../fn/learning/learning-directories-new-post-plain';
import { LearningDirectoriesNewPost$Plain$Params } from '../fn/learning/learning-directories-new-post-plain';
import { learningDirectoriesStudyCategoryGet$Json } from '../fn/learning/learning-directories-study-category-get-json';
import { LearningDirectoriesStudyCategoryGet$Json$Params } from '../fn/learning/learning-directories-study-category-get-json';
import { learningDirectoriesStudyCategoryGet$Plain } from '../fn/learning/learning-directories-study-category-get-plain';
import { LearningDirectoriesStudyCategoryGet$Plain$Params } from '../fn/learning/learning-directories-study-category-get-plain';
import { learningDirectoriyIdDetailGet$Json } from '../fn/learning/learning-directoriy-id-detail-get-json';
import { LearningDirectoriyIdDetailGet$Json$Params } from '../fn/learning/learning-directoriy-id-detail-get-json';
import { learningDirectoriyIdDetailGet$Plain } from '../fn/learning/learning-directoriy-id-detail-get-plain';
import { LearningDirectoriyIdDetailGet$Plain$Params } from '../fn/learning/learning-directoriy-id-detail-get-plain';
import { learningDirectoryIdDelete } from '../fn/learning/learning-directory-id-delete';
import { LearningDirectoryIdDelete$Params } from '../fn/learning/learning-directory-id-delete';
import { learningDirectoryIdFilesGet$Json } from '../fn/learning/learning-directory-id-files-get-json';
import { LearningDirectoryIdFilesGet$Json$Params } from '../fn/learning/learning-directory-id-files-get-json';
import { learningDirectoryIdFilesGet$Plain } from '../fn/learning/learning-directory-id-files-get-plain';
import { LearningDirectoryIdFilesGet$Plain$Params } from '../fn/learning/learning-directory-id-files-get-plain';
import { learningDirectoryIdNewPost$Json } from '../fn/learning/learning-directory-id-new-post-json';
import { LearningDirectoryIdNewPost$Json$Params } from '../fn/learning/learning-directory-id-new-post-json';
import { learningDirectoryIdNewPost$Plain } from '../fn/learning/learning-directory-id-new-post-plain';
import { LearningDirectoryIdNewPost$Plain$Params } from '../fn/learning/learning-directory-id-new-post-plain';
import { learningDirectoryIdParentsGet$Json } from '../fn/learning/learning-directory-id-parents-get-json';
import { LearningDirectoryIdParentsGet$Json$Params } from '../fn/learning/learning-directory-id-parents-get-json';
import { learningDirectoryIdParentsGet$Plain } from '../fn/learning/learning-directory-id-parents-get-plain';
import { LearningDirectoryIdParentsGet$Plain$Params } from '../fn/learning/learning-directory-id-parents-get-plain';
import { learningDirectoryIdSampleImagesDelete } from '../fn/learning/learning-directory-id-sample-images-delete';
import { LearningDirectoryIdSampleImagesDelete$Params } from '../fn/learning/learning-directory-id-sample-images-delete';
import { learningDirectoryIdSampleImagesGet$Json } from '../fn/learning/learning-directory-id-sample-images-get-json';
import { LearningDirectoryIdSampleImagesGet$Json$Params } from '../fn/learning/learning-directory-id-sample-images-get-json';
import { learningDirectoryIdSampleImagesGet$Plain } from '../fn/learning/learning-directory-id-sample-images-get-plain';
import { LearningDirectoryIdSampleImagesGet$Plain$Params } from '../fn/learning/learning-directory-id-sample-images-get-plain';
import { learningDirectoryIdSampleImagesPost } from '../fn/learning/learning-directory-id-sample-images-post';
import { LearningDirectoryIdSampleImagesPost$Params } from '../fn/learning/learning-directory-id-sample-images-post';
import { learningDirectoryIdUpdatePatch } from '../fn/learning/learning-directory-id-update-patch';
import { LearningDirectoryIdUpdatePatch$Params } from '../fn/learning/learning-directory-id-update-patch';
import { learningDirectoryIdVisibilityPatch } from '../fn/learning/learning-directory-id-visibility-patch';
import { LearningDirectoryIdVisibilityPatch$Params } from '../fn/learning/learning-directory-id-visibility-patch';
import { PdfFileDto } from '../models/pdf-file-dto';
import { SampleImageAdminDto } from '../models/sample-image-admin-dto';

@Injectable({ providedIn: 'root' })
export class LearningService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `learningDirectoriesNewPost()` */
  static readonly LearningDirectoriesNewPostPath = '/learning/directories/new';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoriesNewPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoriesNewPost$Plain$Response(params?: LearningDirectoriesNewPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryCreatedResponse>> {
    return learningDirectoriesNewPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoriesNewPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoriesNewPost$Plain(params?: LearningDirectoriesNewPost$Plain$Params, context?: HttpContext): Observable<DirectoryCreatedResponse> {
    return this.learningDirectoriesNewPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DirectoryCreatedResponse>): DirectoryCreatedResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoriesNewPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoriesNewPost$Json$Response(params?: LearningDirectoriesNewPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryCreatedResponse>> {
    return learningDirectoriesNewPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoriesNewPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoriesNewPost$Json(params?: LearningDirectoriesNewPost$Json$Params, context?: HttpContext): Observable<DirectoryCreatedResponse> {
    return this.learningDirectoriesNewPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DirectoryCreatedResponse>): DirectoryCreatedResponse => r.body)
    );
  }

  /** Path part for operation `learningDirectoryIdNewPost()` */
  static readonly LearningDirectoryIdNewPostPath = '/learning/directory/{id}/new';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdNewPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdNewPost$Plain$Response(params: LearningDirectoryIdNewPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryCreatedResponse>> {
    return learningDirectoryIdNewPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdNewPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdNewPost$Plain(params: LearningDirectoryIdNewPost$Plain$Params, context?: HttpContext): Observable<DirectoryCreatedResponse> {
    return this.learningDirectoryIdNewPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DirectoryCreatedResponse>): DirectoryCreatedResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdNewPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdNewPost$Json$Response(params: LearningDirectoryIdNewPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryCreatedResponse>> {
    return learningDirectoryIdNewPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdNewPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdNewPost$Json(params: LearningDirectoryIdNewPost$Json$Params, context?: HttpContext): Observable<DirectoryCreatedResponse> {
    return this.learningDirectoryIdNewPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DirectoryCreatedResponse>): DirectoryCreatedResponse => r.body)
    );
  }

  /** Path part for operation `learningDirectoryIdParentsGet()` */
  static readonly LearningDirectoryIdParentsGetPath = '/learning/directory/{id}/parents';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdParentsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdParentsGet$Plain$Response(params: LearningDirectoryIdParentsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ItemWithNameDto>>> {
    return learningDirectoryIdParentsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdParentsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdParentsGet$Plain(params: LearningDirectoryIdParentsGet$Plain$Params, context?: HttpContext): Observable<Array<ItemWithNameDto>> {
    return this.learningDirectoryIdParentsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ItemWithNameDto>>): Array<ItemWithNameDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdParentsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdParentsGet$Json$Response(params: LearningDirectoryIdParentsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ItemWithNameDto>>> {
    return learningDirectoryIdParentsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdParentsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdParentsGet$Json(params: LearningDirectoryIdParentsGet$Json$Params, context?: HttpContext): Observable<Array<ItemWithNameDto>> {
    return this.learningDirectoryIdParentsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ItemWithNameDto>>): Array<ItemWithNameDto> => r.body)
    );
  }

  /** Path part for operation `learningDirectoryIdVisibilityPatch()` */
  static readonly LearningDirectoryIdVisibilityPatchPath = '/learning/directory/{id}/visibility';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdVisibilityPatch()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdVisibilityPatch$Response(params: LearningDirectoryIdVisibilityPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return learningDirectoryIdVisibilityPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdVisibilityPatch$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdVisibilityPatch(params: LearningDirectoryIdVisibilityPatch$Params, context?: HttpContext): Observable<void> {
    return this.learningDirectoryIdVisibilityPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `learningDirectoryIdUpdatePatch()` */
  static readonly LearningDirectoryIdUpdatePatchPath = '/learning/directory/{id}/update';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdUpdatePatch()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdUpdatePatch$Response(params: LearningDirectoryIdUpdatePatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return learningDirectoryIdUpdatePatch(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdUpdatePatch$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdUpdatePatch(params: LearningDirectoryIdUpdatePatch$Params, context?: HttpContext): Observable<void> {
    return this.learningDirectoryIdUpdatePatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `learningDirectoryIdDelete()` */
  static readonly LearningDirectoryIdDeletePath = '/learning/directory/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdDelete$Response(params: LearningDirectoryIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return learningDirectoryIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdDelete(params: LearningDirectoryIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.learningDirectoryIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `learningDirectoriesFileFileIdDelete()` */
  static readonly LearningDirectoriesFileFileIdDeletePath = '/learning/directories/file/{fileId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoriesFileFileIdDelete$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriesFileFileIdDelete$Plain$Response(params: LearningDirectoriesFileFileIdDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PdfFileDto>> {
    return learningDirectoriesFileFileIdDelete$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoriesFileFileIdDelete$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriesFileFileIdDelete$Plain(params: LearningDirectoriesFileFileIdDelete$Plain$Params, context?: HttpContext): Observable<PdfFileDto> {
    return this.learningDirectoriesFileFileIdDelete$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<PdfFileDto>): PdfFileDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoriesFileFileIdDelete$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriesFileFileIdDelete$Json$Response(params: LearningDirectoriesFileFileIdDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PdfFileDto>> {
    return learningDirectoriesFileFileIdDelete$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoriesFileFileIdDelete$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriesFileFileIdDelete$Json(params: LearningDirectoriesFileFileIdDelete$Json$Params, context?: HttpContext): Observable<PdfFileDto> {
    return this.learningDirectoriesFileFileIdDelete$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<PdfFileDto>): PdfFileDto => r.body)
    );
  }

  /** Path part for operation `learningDirectoriesStudyCategoryGet()` */
  static readonly LearningDirectoriesStudyCategoryGetPath = '/learning/directories/{studyCategory}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoriesStudyCategoryGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriesStudyCategoryGet$Plain$Response(params: LearningDirectoriesStudyCategoryGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DirectoryTreeDto>>> {
    return learningDirectoriesStudyCategoryGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoriesStudyCategoryGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriesStudyCategoryGet$Plain(params: LearningDirectoriesStudyCategoryGet$Plain$Params, context?: HttpContext): Observable<Array<DirectoryTreeDto>> {
    return this.learningDirectoriesStudyCategoryGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DirectoryTreeDto>>): Array<DirectoryTreeDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoriesStudyCategoryGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriesStudyCategoryGet$Json$Response(params: LearningDirectoriesStudyCategoryGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DirectoryTreeDto>>> {
    return learningDirectoriesStudyCategoryGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoriesStudyCategoryGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriesStudyCategoryGet$Json(params: LearningDirectoriesStudyCategoryGet$Json$Params, context?: HttpContext): Observable<Array<DirectoryTreeDto>> {
    return this.learningDirectoriesStudyCategoryGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DirectoryTreeDto>>): Array<DirectoryTreeDto> => r.body)
    );
  }

  /** Path part for operation `learningDirectoriyIdDetailGet()` */
  static readonly LearningDirectoriyIdDetailGetPath = '/learning/directoriy/{id}/detail';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoriyIdDetailGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriyIdDetailGet$Plain$Response(params: LearningDirectoriyIdDetailGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryDetailDto>> {
    return learningDirectoriyIdDetailGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoriyIdDetailGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriyIdDetailGet$Plain(params: LearningDirectoriyIdDetailGet$Plain$Params, context?: HttpContext): Observable<DirectoryDetailDto> {
    return this.learningDirectoriyIdDetailGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DirectoryDetailDto>): DirectoryDetailDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoriyIdDetailGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriyIdDetailGet$Json$Response(params: LearningDirectoriyIdDetailGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryDetailDto>> {
    return learningDirectoriyIdDetailGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoriyIdDetailGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoriyIdDetailGet$Json(params: LearningDirectoriyIdDetailGet$Json$Params, context?: HttpContext): Observable<DirectoryDetailDto> {
    return this.learningDirectoriyIdDetailGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DirectoryDetailDto>): DirectoryDetailDto => r.body)
    );
  }

  /** Path part for operation `learningDirectoryIdSampleImagesGet()` */
  static readonly LearningDirectoryIdSampleImagesGetPath = '/learning/directory/{id}/sample-images';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdSampleImagesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdSampleImagesGet$Plain$Response(params: LearningDirectoryIdSampleImagesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageAdminDto>>> {
    return learningDirectoryIdSampleImagesGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdSampleImagesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdSampleImagesGet$Plain(params: LearningDirectoryIdSampleImagesGet$Plain$Params, context?: HttpContext): Observable<Array<SampleImageAdminDto>> {
    return this.learningDirectoryIdSampleImagesGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SampleImageAdminDto>>): Array<SampleImageAdminDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdSampleImagesGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdSampleImagesGet$Json$Response(params: LearningDirectoryIdSampleImagesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageAdminDto>>> {
    return learningDirectoryIdSampleImagesGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdSampleImagesGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdSampleImagesGet$Json(params: LearningDirectoryIdSampleImagesGet$Json$Params, context?: HttpContext): Observable<Array<SampleImageAdminDto>> {
    return this.learningDirectoryIdSampleImagesGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SampleImageAdminDto>>): Array<SampleImageAdminDto> => r.body)
    );
  }

  /** Path part for operation `learningDirectoryIdSampleImagesPost()` */
  static readonly LearningDirectoryIdSampleImagesPostPath = '/learning/directory/{id}/sample-images';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdSampleImagesPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdSampleImagesPost$Response(params: LearningDirectoryIdSampleImagesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return learningDirectoryIdSampleImagesPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdSampleImagesPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdSampleImagesPost(params: LearningDirectoryIdSampleImagesPost$Params, context?: HttpContext): Observable<void> {
    return this.learningDirectoryIdSampleImagesPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `learningDirectoryIdSampleImagesDelete()` */
  static readonly LearningDirectoryIdSampleImagesDeletePath = '/learning/directory/{id}/sample-images';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdSampleImagesDelete()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdSampleImagesDelete$Response(params: LearningDirectoryIdSampleImagesDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return learningDirectoryIdSampleImagesDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdSampleImagesDelete$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  learningDirectoryIdSampleImagesDelete(params: LearningDirectoryIdSampleImagesDelete$Params, context?: HttpContext): Observable<void> {
    return this.learningDirectoryIdSampleImagesDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `learningDirectoryIdFilesGet()` */
  static readonly LearningDirectoryIdFilesGetPath = '/learning/directory/{id}/files';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdFilesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdFilesGet$Plain$Response(params: LearningDirectoryIdFilesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PdfFileDto>>> {
    return learningDirectoryIdFilesGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdFilesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdFilesGet$Plain(params: LearningDirectoryIdFilesGet$Plain$Params, context?: HttpContext): Observable<Array<PdfFileDto>> {
    return this.learningDirectoryIdFilesGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PdfFileDto>>): Array<PdfFileDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `learningDirectoryIdFilesGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdFilesGet$Json$Response(params: LearningDirectoryIdFilesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PdfFileDto>>> {
    return learningDirectoryIdFilesGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `learningDirectoryIdFilesGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  learningDirectoryIdFilesGet$Json(params: LearningDirectoryIdFilesGet$Json$Params, context?: HttpContext): Observable<Array<PdfFileDto>> {
    return this.learningDirectoryIdFilesGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PdfFileDto>>): Array<PdfFileDto> => r.body)
    );
  }

}
