/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adminSampleImagesBatchDelete } from '../fn/sample-images/admin-sample-images-batch-delete';
import { AdminSampleImagesBatchDelete$Params } from '../fn/sample-images/admin-sample-images-batch-delete';
import { adminSampleImagesBatchPatch } from '../fn/sample-images/admin-sample-images-batch-patch';
import { AdminSampleImagesBatchPatch$Params } from '../fn/sample-images/admin-sample-images-batch-patch';
import { adminSampleImagesGet$Json } from '../fn/sample-images/admin-sample-images-get-json';
import { AdminSampleImagesGet$Json$Params } from '../fn/sample-images/admin-sample-images-get-json';
import { adminSampleImagesGet$Plain } from '../fn/sample-images/admin-sample-images-get-plain';
import { AdminSampleImagesGet$Plain$Params } from '../fn/sample-images/admin-sample-images-get-plain';
import { adminSampleImagesIdFlagDelete } from '../fn/sample-images/admin-sample-images-id-flag-delete';
import { AdminSampleImagesIdFlagDelete$Params } from '../fn/sample-images/admin-sample-images-id-flag-delete';
import { adminSampleImagesIdFlagPost } from '../fn/sample-images/admin-sample-images-id-flag-post';
import { AdminSampleImagesIdFlagPost$Params } from '../fn/sample-images/admin-sample-images-id-flag-post';
import { adminSampleImagesKeywordsIdGet$Json } from '../fn/sample-images/admin-sample-images-keywords-id-get-json';
import { AdminSampleImagesKeywordsIdGet$Json$Params } from '../fn/sample-images/admin-sample-images-keywords-id-get-json';
import { adminSampleImagesKeywordsIdGet$Plain } from '../fn/sample-images/admin-sample-images-keywords-id-get-plain';
import { AdminSampleImagesKeywordsIdGet$Plain$Params } from '../fn/sample-images/admin-sample-images-keywords-id-get-plain';
import { SampleImageAdminDto } from '../models/sample-image-admin-dto';

@Injectable({ providedIn: 'root' })
export class SampleImagesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `adminSampleImagesGet()` */
  static readonly AdminSampleImagesGetPath = '/admin/sample-images';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminSampleImagesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminSampleImagesGet$Plain$Response(params?: AdminSampleImagesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageAdminDto>>> {
    return adminSampleImagesGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminSampleImagesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminSampleImagesGet$Plain(params?: AdminSampleImagesGet$Plain$Params, context?: HttpContext): Observable<Array<SampleImageAdminDto>> {
    return this.adminSampleImagesGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SampleImageAdminDto>>): Array<SampleImageAdminDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminSampleImagesGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminSampleImagesGet$Json$Response(params?: AdminSampleImagesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageAdminDto>>> {
    return adminSampleImagesGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminSampleImagesGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminSampleImagesGet$Json(params?: AdminSampleImagesGet$Json$Params, context?: HttpContext): Observable<Array<SampleImageAdminDto>> {
    return this.adminSampleImagesGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SampleImageAdminDto>>): Array<SampleImageAdminDto> => r.body)
    );
  }

  /** Path part for operation `adminSampleImagesBatchDelete()` */
  static readonly AdminSampleImagesBatchDeletePath = '/admin/sample-images/batch';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminSampleImagesBatchDelete()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adminSampleImagesBatchDelete$Response(params?: AdminSampleImagesBatchDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return adminSampleImagesBatchDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminSampleImagesBatchDelete$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adminSampleImagesBatchDelete(params?: AdminSampleImagesBatchDelete$Params, context?: HttpContext): Observable<void> {
    return this.adminSampleImagesBatchDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `adminSampleImagesBatchPatch()` */
  static readonly AdminSampleImagesBatchPatchPath = '/admin/sample-images/batch';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminSampleImagesBatchPatch()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adminSampleImagesBatchPatch$Response(params?: AdminSampleImagesBatchPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return adminSampleImagesBatchPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminSampleImagesBatchPatch$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adminSampleImagesBatchPatch(params?: AdminSampleImagesBatchPatch$Params, context?: HttpContext): Observable<void> {
    return this.adminSampleImagesBatchPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `adminSampleImagesIdFlagPost()` */
  static readonly AdminSampleImagesIdFlagPostPath = '/admin/sample-images/{id}/flag';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminSampleImagesIdFlagPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adminSampleImagesIdFlagPost$Response(params: AdminSampleImagesIdFlagPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return adminSampleImagesIdFlagPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminSampleImagesIdFlagPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adminSampleImagesIdFlagPost(params: AdminSampleImagesIdFlagPost$Params, context?: HttpContext): Observable<void> {
    return this.adminSampleImagesIdFlagPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `adminSampleImagesIdFlagDelete()` */
  static readonly AdminSampleImagesIdFlagDeletePath = '/admin/sample-images/{id}/flag';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminSampleImagesIdFlagDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminSampleImagesIdFlagDelete$Response(params: AdminSampleImagesIdFlagDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return adminSampleImagesIdFlagDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminSampleImagesIdFlagDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminSampleImagesIdFlagDelete(params: AdminSampleImagesIdFlagDelete$Params, context?: HttpContext): Observable<void> {
    return this.adminSampleImagesIdFlagDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `adminSampleImagesKeywordsIdGet()` */
  static readonly AdminSampleImagesKeywordsIdGetPath = '/admin/sample-images/keywords/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminSampleImagesKeywordsIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminSampleImagesKeywordsIdGet$Plain$Response(params: AdminSampleImagesKeywordsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return adminSampleImagesKeywordsIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminSampleImagesKeywordsIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminSampleImagesKeywordsIdGet$Plain(params: AdminSampleImagesKeywordsIdGet$Plain$Params, context?: HttpContext): Observable<Array<string>> {
    return this.adminSampleImagesKeywordsIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminSampleImagesKeywordsIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminSampleImagesKeywordsIdGet$Json$Response(params: AdminSampleImagesKeywordsIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    return adminSampleImagesKeywordsIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminSampleImagesKeywordsIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminSampleImagesKeywordsIdGet$Json(params: AdminSampleImagesKeywordsIdGet$Json$Params, context?: HttpContext): Observable<Array<string>> {
    return this.adminSampleImagesKeywordsIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

}
