/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrgansListDto } from '../../models/organs-list-dto';

export interface AssetsOrganTileListGet$Json$Params {
}

export function assetsOrganTileListGet$Json(http: HttpClient, rootUrl: string, params?: AssetsOrganTileListGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<OrgansListDto>> {
  const rb = new RequestBuilder(rootUrl, assetsOrganTileListGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrgansListDto>;
    })
  );
}

assetsOrganTileListGet$Json.PATH = '/assets/organ-tile-list';
