/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrganDetailDto } from '../../models/organ-detail-dto';

export interface AssetsOrganDetailIdGet$Plain$Params {
  id: number;
}

export function assetsOrganDetailIdGet$Plain(http: HttpClient, rootUrl: string, params: AssetsOrganDetailIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OrganDetailDto>> {
  const rb = new RequestBuilder(rootUrl, assetsOrganDetailIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrganDetailDto>;
    })
  );
}

assetsOrganDetailIdGet$Plain.PATH = '/assets/organ-detail/{id}';
