/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BodySystemListDto } from '../../models/body-system-list-dto';

export interface AssetsBodySystemListGet$Plain$Params {
}

export function assetsBodySystemListGet$Plain(http: HttpClient, rootUrl: string, params?: AssetsBodySystemListGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BodySystemListDto>> {
  const rb = new RequestBuilder(rootUrl, assetsBodySystemListGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BodySystemListDto>;
    })
  );
}

assetsBodySystemListGet$Plain.PATH = '/assets/body-system-list';
