/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SampleImageDiagnosisDto } from '../../models/sample-image-diagnosis-dto';

export interface AssetsSamplesImagesAllGet$Json$Params {
}

export function assetsSamplesImagesAllGet$Json(http: HttpClient, rootUrl: string, params?: AssetsSamplesImagesAllGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageDiagnosisDto>>> {
  const rb = new RequestBuilder(rootUrl, assetsSamplesImagesAllGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SampleImageDiagnosisDto>>;
    })
  );
}

assetsSamplesImagesAllGet$Json.PATH = '/assets/samples-images-all';
