/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SampleImageDiagnosisDto } from '../../models/sample-image-diagnosis-dto';

export interface ClassworkDirectoryIdSampleImagesGet$Json$Params {
  id: number;
}

export function classworkDirectoryIdSampleImagesGet$Json(http: HttpClient, rootUrl: string, params: ClassworkDirectoryIdSampleImagesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageDiagnosisDto>>> {
  const rb = new RequestBuilder(rootUrl, classworkDirectoryIdSampleImagesGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SampleImageDiagnosisDto>>;
    })
  );
}

classworkDirectoryIdSampleImagesGet$Json.PATH = '/classwork/directory/{id}/sample-images';
