/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PdfFileDto } from '../../models/pdf-file-dto';

export interface ClassworkDirectoryIdFilesGet$Plain$Params {
  id: number;
}

export function classworkDirectoryIdFilesGet$Plain(http: HttpClient, rootUrl: string, params: ClassworkDirectoryIdFilesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PdfFileDto>>> {
  const rb = new RequestBuilder(rootUrl, classworkDirectoryIdFilesGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PdfFileDto>>;
    })
  );
}

classworkDirectoryIdFilesGet$Plain.PATH = '/classwork/directory/{id}/files';
