/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DirectoryTreeDto } from '../../models/directory-tree-dto';

export interface LearningDirectoriesStudyCategoryGet$Plain$Params {
  studyCategory: string;
}

export function learningDirectoriesStudyCategoryGet$Plain(http: HttpClient, rootUrl: string, params: LearningDirectoriesStudyCategoryGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DirectoryTreeDto>>> {
  const rb = new RequestBuilder(rootUrl, learningDirectoriesStudyCategoryGet$Plain.PATH, 'get');
  if (params) {
    rb.path('studyCategory', params.studyCategory, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DirectoryTreeDto>>;
    })
  );
}

learningDirectoriesStudyCategoryGet$Plain.PATH = '/learning/directories/{studyCategory}';
