/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BodySystemDto } from '../models/body-system-dto';
export interface BodySystemListDto {
  bodySystems: Array<BodySystemDto>;
}
