/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Organ } from '../models/organ';
import { PdfFile } from '../models/pdf-file';
export interface BodySystem {
  description: string;
  iconPath: string;
  id: number;
  name: string;
  organs?: Array<Organ>;
  pdfs?: Array<PdfFile>;
}
