/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BodySystemDescriptionDto } from '../models/body-system-description-dto';
import { SampleImageDiagnosisDto } from '../models/sample-image-diagnosis-dto';
export interface BodySystemDetailDto {
  bodySystemDescription: BodySystemDescriptionDto;
  sampleImages: Array<SampleImageDiagnosisDto>;
}
