/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DirectoryListItemDto } from '../models/directory-list-item-dto';
import { PdfFileDto } from '../models/pdf-file-dto';
export interface DirectoryDetailDto {
  children?: Array<DirectoryListItemDto>;
  description?: string | null;
  files?: Array<PdfFileDto>;
  id: number;
  isPublic: boolean;
  keyWords?: string | null;
  level: number;
  name: string;
}
