/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganDescriptionDto } from '../models/organ-description-dto';
import { PdfFile } from '../models/pdf-file';
import { SampleImageDiagnosisDto } from '../models/sample-image-diagnosis-dto';
export interface OrganDetailDto {
  organDescription: OrganDescriptionDto;
  organPdf?: PdfFile;
  sampleImages: Array<SampleImageDiagnosisDto>;
}
