/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BodySystem } from '../models/body-system';
import { PdfFile } from '../models/pdf-file';
export interface Organ {
  bodySystems: Array<BodySystem>;
  description: string;
  iconPath: string;
  id: number;
  name: string;
  pdfs?: Array<PdfFile>;
}
