/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BodySystem } from '../models/body-system';
import { Directory } from '../models/directory';
import { Organ } from '../models/organ';
export interface PdfFile {
  bodySystem?: BodySystem;
  directory?: Directory;
  directoryId?: number | null;
  id: number;
  name: string;
  organ?: Organ;
  path: string;
}
