/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DimensionMeter } from '../models/dimension-meter';
export interface PixelInfo {
  height?: DimensionMeter;
  type?: string;
  width?: DimensionMeter;
}
