/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SampleImageAnnotationDto } from '../models/sample-image-annotation-dto';
export interface SampleImageAnnotationsListDto {
  sampleImageAnnotations: Array<SampleImageAnnotationDto>;
}
