/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FlagTypeDto } from '../models/flag-type-dto';
import { PdfFile } from '../models/pdf-file';
export interface SampleImageAdminDto {
  bodySystemNames: Array<string>;
  caustryFile?: PdfFile;
  flagType?: FlagTypeDto;
  hasAnnotation: boolean;
  id: number;
  isVisible: boolean;
  keyWords?: string | null;
  name: string;
  note?: string | null;
  organName: string;
  path: string;
}
