/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AdminUploadSampleImageDataPost$Json$Params {
      body?: {
'AnnotationFile'?: Blob;
'SampleImageFileName'?: string;
'OrganId'?: number;
'KeyWords'?: string;
}
}

export function adminUploadSampleImageDataPost$Json(http: HttpClient, rootUrl: string, params?: AdminUploadSampleImageDataPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, adminUploadSampleImageDataPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

adminUploadSampleImageDataPost$Json.PATH = '/admin/upload-sample-image-data';
