/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageSize } from '../models/image-size';
import { PixelInfo } from '../models/pixel-info';
import { PixelsPerMeter } from '../models/pixels-per-meter';
import { TileInfo } from '../models/tile-info';
export interface SampleImageMetadataDto {
  domains?: Array<string>;
  fillColor?: number;
  format?: string;
  levels?: number;
  magnification?: number;
  pixel?: PixelInfo;
  pixelsPerMeter?: PixelsPerMeter;
  resolution?: number;
  size?: ImageSize;
  tile?: TileInfo;
}
