/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PdfFile } from '../models/pdf-file';
export interface SampleImageDto {
  caustryFile?: PdfFile;
  diagnosis: string;
  hasAnnotation: boolean;
  id: number;
  isFavorite: boolean;
  keyWords?: string | null;
  name: string;
  note?: string | null;
  path: string;
}
