/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Diagnosis } from '../models/diagnosis';
import { Directory } from '../models/directory';
import { Organ } from '../models/organ';
import { PdfFile } from '../models/pdf-file';
export interface SampleImage {
  caustryFile?: PdfFile;
  caustryFileID?: number | null;
  diagnosis?: Diagnosis;
  diagnosisID?: number | null;
  groupId: string;
  id?: number;
  isVisible?: boolean;
  keyWords?: string | null;
  lastModified: string;
  metadata?: string | null;
  name?: string | null;
  organ?: Organ;
  organID?: number | null;
  parentDirectories?: Array<Directory>;
  path?: string | null;
  state: string;
}
