/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DiangosesListDto } from '../../models/diangoses-list-dto';

export interface AssetsDiagnosesListGet$Plain$Params {
}

export function assetsDiagnosesListGet$Plain(http: HttpClient, rootUrl: string, params?: AssetsDiagnosesListGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DiangosesListDto>> {
  const rb = new RequestBuilder(rootUrl, assetsDiagnosesListGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DiangosesListDto>;
    })
  );
}

assetsDiagnosesListGet$Plain.PATH = '/assets/diagnoses-list';
