/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IconPathDto } from '../../models/icon-path-dto';

export interface AssetsBodySystemIconPathIdGet$Plain$Params {
  id: number;
}

export function assetsBodySystemIconPathIdGet$Plain(http: HttpClient, rootUrl: string, params: AssetsBodySystemIconPathIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<IconPathDto>> {
  const rb = new RequestBuilder(rootUrl, assetsBodySystemIconPathIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IconPathDto>;
    })
  );
}

assetsBodySystemIconPathIdGet$Plain.PATH = '/assets/body-system-icon-path/{id}';
