/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConversionJobDto } from '../../models/conversion-job-dto';

export interface ConversionJobGet$Plain$Params {
}

export function conversionJobGet$Plain(http: HttpClient, rootUrl: string, params?: ConversionJobGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConversionJobDto>>> {
  const rb = new RequestBuilder(rootUrl, conversionJobGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ConversionJobDto>>;
    })
  );
}

conversionJobGet$Plain.PATH = '/conversion/job';
