/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConversionJobDto } from '../../models/conversion-job-dto';

export interface ConversionJobSampleImageIdPatch$Json$Params {
  sampleImageId: number;
      body?: ConversionJobDto
}

export function conversionJobSampleImageIdPatch$Json(http: HttpClient, rootUrl: string, params: ConversionJobSampleImageIdPatch$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ConversionJobDto>> {
  const rb = new RequestBuilder(rootUrl, conversionJobSampleImageIdPatch$Json.PATH, 'patch');
  if (params) {
    rb.path('sampleImageId', params.sampleImageId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConversionJobDto>;
    })
  );
}

conversionJobSampleImageIdPatch$Json.PATH = '/conversion/job/{sampleImageId}';
