/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DirectoryDetailDto } from '../../models/directory-detail-dto';

export interface LearningDirectoriyIdDetailGet$Plain$Params {
  id: number;
}

export function learningDirectoriyIdDetailGet$Plain(http: HttpClient, rootUrl: string, params: LearningDirectoriyIdDetailGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryDetailDto>> {
  const rb = new RequestBuilder(rootUrl, learningDirectoriyIdDetailGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DirectoryDetailDto>;
    })
  );
}

learningDirectoriyIdDetailGet$Plain.PATH = '/learning/directoriy/{id}/detail';
