/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DirectoryCreatedResponse } from '../../models/directory-created-response';
import { NewDirectoryRequest } from '../../models/new-directory-request';

export interface LearningDirectoryIdNewPost$Json$Params {
  id: number;
      body?: NewDirectoryRequest
}

export function learningDirectoryIdNewPost$Json(http: HttpClient, rootUrl: string, params: LearningDirectoryIdNewPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryCreatedResponse>> {
  const rb = new RequestBuilder(rootUrl, learningDirectoryIdNewPost$Json.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DirectoryCreatedResponse>;
    })
  );
}

learningDirectoryIdNewPost$Json.PATH = '/learning/directory/{id}/new';
