/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PdfFileDto } from '../../models/pdf-file-dto';

export interface LearningDirectoriesFileFileIdDelete$Json$Params {
  fileId: number;
}

export function learningDirectoriesFileFileIdDelete$Json(http: HttpClient, rootUrl: string, params: LearningDirectoriesFileFileIdDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PdfFileDto>> {
  const rb = new RequestBuilder(rootUrl, learningDirectoriesFileFileIdDelete$Json.PATH, 'delete');
  if (params) {
    rb.path('fileId', params.fileId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PdfFileDto>;
    })
  );
}

learningDirectoriesFileFileIdDelete$Json.PATH = '/learning/directories/file/{fileId}';
