/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ConversionJobDto } from '../models/conversion-job-dto';
import { conversionJobGet$Json } from '../fn/conversion/conversion-job-get-json';
import { ConversionJobGet$Json$Params } from '../fn/conversion/conversion-job-get-json';
import { conversionJobGet$Plain } from '../fn/conversion/conversion-job-get-plain';
import { ConversionJobGet$Plain$Params } from '../fn/conversion/conversion-job-get-plain';
import { conversionJobSampleImageIdPatch$Json } from '../fn/conversion/conversion-job-sample-image-id-patch-json';
import { ConversionJobSampleImageIdPatch$Json$Params } from '../fn/conversion/conversion-job-sample-image-id-patch-json';
import { conversionJobSampleImageIdPatch$Plain } from '../fn/conversion/conversion-job-sample-image-id-patch-plain';
import { ConversionJobSampleImageIdPatch$Plain$Params } from '../fn/conversion/conversion-job-sample-image-id-patch-plain';

@Injectable({ providedIn: 'root' })
export class ConversionService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `conversionJobGet()` */
  static readonly ConversionJobGetPath = '/conversion/job';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `conversionJobGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  conversionJobGet$Plain$Response(params?: ConversionJobGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConversionJobDto>>> {
    return conversionJobGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `conversionJobGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  conversionJobGet$Plain(params?: ConversionJobGet$Plain$Params, context?: HttpContext): Observable<Array<ConversionJobDto>> {
    return this.conversionJobGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ConversionJobDto>>): Array<ConversionJobDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `conversionJobGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  conversionJobGet$Json$Response(params?: ConversionJobGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ConversionJobDto>>> {
    return conversionJobGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `conversionJobGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  conversionJobGet$Json(params?: ConversionJobGet$Json$Params, context?: HttpContext): Observable<Array<ConversionJobDto>> {
    return this.conversionJobGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ConversionJobDto>>): Array<ConversionJobDto> => r.body)
    );
  }

  /** Path part for operation `conversionJobSampleImageIdPatch()` */
  static readonly ConversionJobSampleImageIdPatchPath = '/conversion/job/{sampleImageId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `conversionJobSampleImageIdPatch$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  conversionJobSampleImageIdPatch$Plain$Response(params: ConversionJobSampleImageIdPatch$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ConversionJobDto>> {
    return conversionJobSampleImageIdPatch$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `conversionJobSampleImageIdPatch$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  conversionJobSampleImageIdPatch$Plain(params: ConversionJobSampleImageIdPatch$Plain$Params, context?: HttpContext): Observable<ConversionJobDto> {
    return this.conversionJobSampleImageIdPatch$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<ConversionJobDto>): ConversionJobDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `conversionJobSampleImageIdPatch$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  conversionJobSampleImageIdPatch$Json$Response(params: ConversionJobSampleImageIdPatch$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ConversionJobDto>> {
    return conversionJobSampleImageIdPatch$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `conversionJobSampleImageIdPatch$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  conversionJobSampleImageIdPatch$Json(params: ConversionJobSampleImageIdPatch$Json$Params, context?: HttpContext): Observable<ConversionJobDto> {
    return this.conversionJobSampleImageIdPatch$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<ConversionJobDto>): ConversionJobDto => r.body)
    );
  }

}
