/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DirectoryCreatedResponse } from '../../models/directory-created-response';
import { NewRootDirectoryRequest } from '../../models/new-root-directory-request';

export interface LearningDirectoriesNewPost$Plain$Params {
      body?: NewRootDirectoryRequest
}

export function learningDirectoriesNewPost$Plain(http: HttpClient, rootUrl: string, params?: LearningDirectoriesNewPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryCreatedResponse>> {
  const rb = new RequestBuilder(rootUrl, learningDirectoriesNewPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DirectoryCreatedResponse>;
    })
  );
}

learningDirectoriesNewPost$Plain.PATH = '/learning/directories/new';
