/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemWithNameDto } from '../../models/item-with-name-dto';

export interface LearningDirectoryIdParentsGet$Json$Params {
  id: number;
}

export function learningDirectoryIdParentsGet$Json(http: HttpClient, rootUrl: string, params: LearningDirectoryIdParentsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ItemWithNameDto>>> {
  const rb = new RequestBuilder(rootUrl, learningDirectoryIdParentsGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ItemWithNameDto>>;
    })
  );
}

learningDirectoryIdParentsGet$Json.PATH = '/learning/directory/{id}/parents';
