/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { adminCaustryIdDelete } from '../fn/admin/admin-caustry-id-delete';
import { AdminCaustryIdDelete$Params } from '../fn/admin/admin-caustry-id-delete';
import { adminEditSamplePost } from '../fn/admin/admin-edit-sample-post';
import { AdminEditSamplePost$Params } from '../fn/admin/admin-edit-sample-post';
import { adminFlagIdDelete } from '../fn/admin/admin-flag-id-delete';
import { AdminFlagIdDelete$Params } from '../fn/admin/admin-flag-id-delete';
import { adminFlagsGet$Json } from '../fn/admin/admin-flags-get-json';
import { AdminFlagsGet$Json$Params } from '../fn/admin/admin-flags-get-json';
import { adminFlagsGet$Plain } from '../fn/admin/admin-flags-get-plain';
import { AdminFlagsGet$Plain$Params } from '../fn/admin/admin-flags-get-plain';
import { adminFlagsPost } from '../fn/admin/admin-flags-post';
import { AdminFlagsPost$Params } from '../fn/admin/admin-flags-post';
import { adminUploadSampleImageDataPost$Json } from '../fn/admin/admin-upload-sample-image-data-post-json';
import { AdminUploadSampleImageDataPost$Json$Params } from '../fn/admin/admin-upload-sample-image-data-post-json';
import { adminUploadSampleImageDataPost$Plain } from '../fn/admin/admin-upload-sample-image-data-post-plain';
import { AdminUploadSampleImageDataPost$Plain$Params } from '../fn/admin/admin-upload-sample-image-data-post-plain';
import { FlagTypeDto } from '../models/flag-type-dto';

@Injectable({ providedIn: 'root' })
export class AdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `adminUploadSampleImageDataPost()` */
  static readonly AdminUploadSampleImageDataPostPath = '/admin/upload-sample-image-data';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminUploadSampleImageDataPost$Plain()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  adminUploadSampleImageDataPost$Plain$Response(params?: AdminUploadSampleImageDataPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return adminUploadSampleImageDataPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminUploadSampleImageDataPost$Plain$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  adminUploadSampleImageDataPost$Plain(params?: AdminUploadSampleImageDataPost$Plain$Params, context?: HttpContext): Observable<string> {
    return this.adminUploadSampleImageDataPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminUploadSampleImageDataPost$Json()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  adminUploadSampleImageDataPost$Json$Response(params?: AdminUploadSampleImageDataPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return adminUploadSampleImageDataPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminUploadSampleImageDataPost$Json$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  adminUploadSampleImageDataPost$Json(params?: AdminUploadSampleImageDataPost$Json$Params, context?: HttpContext): Observable<string> {
    return this.adminUploadSampleImageDataPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `adminFlagsGet()` */
  static readonly AdminFlagsGetPath = '/admin/flags';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminFlagsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminFlagsGet$Plain$Response(params?: AdminFlagsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FlagTypeDto>>> {
    return adminFlagsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminFlagsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminFlagsGet$Plain(params?: AdminFlagsGet$Plain$Params, context?: HttpContext): Observable<Array<FlagTypeDto>> {
    return this.adminFlagsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FlagTypeDto>>): Array<FlagTypeDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminFlagsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminFlagsGet$Json$Response(params?: AdminFlagsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FlagTypeDto>>> {
    return adminFlagsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminFlagsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminFlagsGet$Json(params?: AdminFlagsGet$Json$Params, context?: HttpContext): Observable<Array<FlagTypeDto>> {
    return this.adminFlagsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FlagTypeDto>>): Array<FlagTypeDto> => r.body)
    );
  }

  /** Path part for operation `adminFlagsPost()` */
  static readonly AdminFlagsPostPath = '/admin/flags';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminFlagsPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adminFlagsPost$Response(params?: AdminFlagsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return adminFlagsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminFlagsPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adminFlagsPost(params?: AdminFlagsPost$Params, context?: HttpContext): Observable<void> {
    return this.adminFlagsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `adminEditSamplePost()` */
  static readonly AdminEditSamplePostPath = '/admin/edit-sample';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminEditSamplePost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adminEditSamplePost$Response(params?: AdminEditSamplePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return adminEditSamplePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminEditSamplePost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  adminEditSamplePost(params?: AdminEditSamplePost$Params, context?: HttpContext): Observable<void> {
    return this.adminEditSamplePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `adminFlagIdDelete()` */
  static readonly AdminFlagIdDeletePath = '/admin/flag/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminFlagIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminFlagIdDelete$Response(params: AdminFlagIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return adminFlagIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminFlagIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminFlagIdDelete(params: AdminFlagIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.adminFlagIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `adminCaustryIdDelete()` */
  static readonly AdminCaustryIdDeletePath = '/admin/caustry/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `adminCaustryIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminCaustryIdDelete$Response(params: AdminCaustryIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return adminCaustryIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `adminCaustryIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  adminCaustryIdDelete(params: AdminCaustryIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.adminCaustryIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
