/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { assetsBodySystemDetailIdGet$Json } from '../fn/assets/assets-body-system-detail-id-get-json';
import { AssetsBodySystemDetailIdGet$Json$Params } from '../fn/assets/assets-body-system-detail-id-get-json';
import { assetsBodySystemDetailIdGet$Plain } from '../fn/assets/assets-body-system-detail-id-get-plain';
import { AssetsBodySystemDetailIdGet$Plain$Params } from '../fn/assets/assets-body-system-detail-id-get-plain';
import { assetsBodySystemIconPathIdGet$Json } from '../fn/assets/assets-body-system-icon-path-id-get-json';
import { AssetsBodySystemIconPathIdGet$Json$Params } from '../fn/assets/assets-body-system-icon-path-id-get-json';
import { assetsBodySystemIconPathIdGet$Plain } from '../fn/assets/assets-body-system-icon-path-id-get-plain';
import { AssetsBodySystemIconPathIdGet$Plain$Params } from '../fn/assets/assets-body-system-icon-path-id-get-plain';
import { assetsBodySystemListGet$Json } from '../fn/assets/assets-body-system-list-get-json';
import { AssetsBodySystemListGet$Json$Params } from '../fn/assets/assets-body-system-list-get-json';
import { assetsBodySystemListGet$Plain } from '../fn/assets/assets-body-system-list-get-plain';
import { AssetsBodySystemListGet$Plain$Params } from '../fn/assets/assets-body-system-list-get-plain';
import { assetsDiagnosesListGet$Json } from '../fn/assets/assets-diagnoses-list-get-json';
import { AssetsDiagnosesListGet$Json$Params } from '../fn/assets/assets-diagnoses-list-get-json';
import { assetsDiagnosesListGet$Plain } from '../fn/assets/assets-diagnoses-list-get-plain';
import { AssetsDiagnosesListGet$Plain$Params } from '../fn/assets/assets-diagnoses-list-get-plain';
import { assetsOrganDetailIdGet$Json } from '../fn/assets/assets-organ-detail-id-get-json';
import { AssetsOrganDetailIdGet$Json$Params } from '../fn/assets/assets-organ-detail-id-get-json';
import { assetsOrganDetailIdGet$Plain } from '../fn/assets/assets-organ-detail-id-get-plain';
import { AssetsOrganDetailIdGet$Plain$Params } from '../fn/assets/assets-organ-detail-id-get-plain';
import { assetsOrganIconPathIdGet$Json } from '../fn/assets/assets-organ-icon-path-id-get-json';
import { AssetsOrganIconPathIdGet$Json$Params } from '../fn/assets/assets-organ-icon-path-id-get-json';
import { assetsOrganIconPathIdGet$Plain } from '../fn/assets/assets-organ-icon-path-id-get-plain';
import { AssetsOrganIconPathIdGet$Plain$Params } from '../fn/assets/assets-organ-icon-path-id-get-plain';
import { assetsOrganTileListGet$Json } from '../fn/assets/assets-organ-tile-list-get-json';
import { AssetsOrganTileListGet$Json$Params } from '../fn/assets/assets-organ-tile-list-get-json';
import { assetsOrganTileListGet$Plain } from '../fn/assets/assets-organ-tile-list-get-plain';
import { AssetsOrganTileListGet$Plain$Params } from '../fn/assets/assets-organ-tile-list-get-plain';
import { assetsSampleImageAnnotationsIdGet$Json } from '../fn/assets/assets-sample-image-annotations-id-get-json';
import { AssetsSampleImageAnnotationsIdGet$Json$Params } from '../fn/assets/assets-sample-image-annotations-id-get-json';
import { assetsSampleImageAnnotationsIdGet$Plain } from '../fn/assets/assets-sample-image-annotations-id-get-plain';
import { AssetsSampleImageAnnotationsIdGet$Plain$Params } from '../fn/assets/assets-sample-image-annotations-id-get-plain';
import { assetsSampleImageMetadataSampleIdGet$Json } from '../fn/assets/assets-sample-image-metadata-sample-id-get-json';
import { AssetsSampleImageMetadataSampleIdGet$Json$Params } from '../fn/assets/assets-sample-image-metadata-sample-id-get-json';
import { assetsSampleImageMetadataSampleIdGet$Plain } from '../fn/assets/assets-sample-image-metadata-sample-id-get-plain';
import { AssetsSampleImageMetadataSampleIdGet$Plain$Params } from '../fn/assets/assets-sample-image-metadata-sample-id-get-plain';
import { assetsSampleImageSampleIdFavoriteDelete } from '../fn/assets/assets-sample-image-sample-id-favorite-delete';
import { AssetsSampleImageSampleIdFavoriteDelete$Params } from '../fn/assets/assets-sample-image-sample-id-favorite-delete';
import { assetsSampleImageSampleIdFavoritePost } from '../fn/assets/assets-sample-image-sample-id-favorite-post';
import { AssetsSampleImageSampleIdFavoritePost$Params } from '../fn/assets/assets-sample-image-sample-id-favorite-post';
import { assetsSampleImageSampleIdGet$Json } from '../fn/assets/assets-sample-image-sample-id-get-json';
import { AssetsSampleImageSampleIdGet$Json$Params } from '../fn/assets/assets-sample-image-sample-id-get-json';
import { assetsSampleImageSampleIdGet$Plain } from '../fn/assets/assets-sample-image-sample-id-get-plain';
import { AssetsSampleImageSampleIdGet$Plain$Params } from '../fn/assets/assets-sample-image-sample-id-get-plain';
import { assetsSampleImageSampleIdNotePost } from '../fn/assets/assets-sample-image-sample-id-note-post';
import { AssetsSampleImageSampleIdNotePost$Params } from '../fn/assets/assets-sample-image-sample-id-note-post';
import { assetsSamplesImagesAllGet$Json } from '../fn/assets/assets-samples-images-all-get-json';
import { AssetsSamplesImagesAllGet$Json$Params } from '../fn/assets/assets-samples-images-all-get-json';
import { assetsSamplesImagesAllGet$Plain } from '../fn/assets/assets-samples-images-all-get-plain';
import { AssetsSamplesImagesAllGet$Plain$Params } from '../fn/assets/assets-samples-images-all-get-plain';
import { BodySystemDetailDto } from '../models/body-system-detail-dto';
import { BodySystemListDto } from '../models/body-system-list-dto';
import { DiangosesListDto } from '../models/diangoses-list-dto';
import { IconPathDto } from '../models/icon-path-dto';
import { OrganDetailDto } from '../models/organ-detail-dto';
import { OrgansListDto } from '../models/organs-list-dto';
import { SampleImageAnnotationsListDto } from '../models/sample-image-annotations-list-dto';
import { SampleImageDiagnosisDto } from '../models/sample-image-diagnosis-dto';
import { SampleImageDto } from '../models/sample-image-dto';
import { SampleImageMetadataDto } from '../models/sample-image-metadata-dto';

@Injectable({ providedIn: 'root' })
export class AssetsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `assetsSamplesImagesAllGet()` */
  static readonly AssetsSamplesImagesAllGetPath = '/assets/samples-images-all';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSamplesImagesAllGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSamplesImagesAllGet$Plain$Response(params?: AssetsSamplesImagesAllGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageDiagnosisDto>>> {
    return assetsSamplesImagesAllGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSamplesImagesAllGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSamplesImagesAllGet$Plain(params?: AssetsSamplesImagesAllGet$Plain$Params, context?: HttpContext): Observable<Array<SampleImageDiagnosisDto>> {
    return this.assetsSamplesImagesAllGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SampleImageDiagnosisDto>>): Array<SampleImageDiagnosisDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSamplesImagesAllGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSamplesImagesAllGet$Json$Response(params?: AssetsSamplesImagesAllGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageDiagnosisDto>>> {
    return assetsSamplesImagesAllGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSamplesImagesAllGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSamplesImagesAllGet$Json(params?: AssetsSamplesImagesAllGet$Json$Params, context?: HttpContext): Observable<Array<SampleImageDiagnosisDto>> {
    return this.assetsSamplesImagesAllGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SampleImageDiagnosisDto>>): Array<SampleImageDiagnosisDto> => r.body)
    );
  }

  /** Path part for operation `assetsOrganTileListGet()` */
  static readonly AssetsOrganTileListGetPath = '/assets/organ-tile-list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsOrganTileListGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganTileListGet$Plain$Response(params?: AssetsOrganTileListGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OrgansListDto>> {
    return assetsOrganTileListGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsOrganTileListGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganTileListGet$Plain(params?: AssetsOrganTileListGet$Plain$Params, context?: HttpContext): Observable<OrgansListDto> {
    return this.assetsOrganTileListGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrgansListDto>): OrgansListDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsOrganTileListGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganTileListGet$Json$Response(params?: AssetsOrganTileListGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<OrgansListDto>> {
    return assetsOrganTileListGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsOrganTileListGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganTileListGet$Json(params?: AssetsOrganTileListGet$Json$Params, context?: HttpContext): Observable<OrgansListDto> {
    return this.assetsOrganTileListGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrgansListDto>): OrgansListDto => r.body)
    );
  }

  /** Path part for operation `assetsDiagnosesListGet()` */
  static readonly AssetsDiagnosesListGetPath = '/assets/diagnoses-list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsDiagnosesListGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsDiagnosesListGet$Plain$Response(params?: AssetsDiagnosesListGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DiangosesListDto>> {
    return assetsDiagnosesListGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsDiagnosesListGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsDiagnosesListGet$Plain(params?: AssetsDiagnosesListGet$Plain$Params, context?: HttpContext): Observable<DiangosesListDto> {
    return this.assetsDiagnosesListGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DiangosesListDto>): DiangosesListDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsDiagnosesListGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsDiagnosesListGet$Json$Response(params?: AssetsDiagnosesListGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DiangosesListDto>> {
    return assetsDiagnosesListGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsDiagnosesListGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsDiagnosesListGet$Json(params?: AssetsDiagnosesListGet$Json$Params, context?: HttpContext): Observable<DiangosesListDto> {
    return this.assetsDiagnosesListGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DiangosesListDto>): DiangosesListDto => r.body)
    );
  }

  /** Path part for operation `assetsOrganDetailIdGet()` */
  static readonly AssetsOrganDetailIdGetPath = '/assets/organ-detail/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsOrganDetailIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganDetailIdGet$Plain$Response(params: AssetsOrganDetailIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<OrganDetailDto>> {
    return assetsOrganDetailIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsOrganDetailIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganDetailIdGet$Plain(params: AssetsOrganDetailIdGet$Plain$Params, context?: HttpContext): Observable<OrganDetailDto> {
    return this.assetsOrganDetailIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrganDetailDto>): OrganDetailDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsOrganDetailIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganDetailIdGet$Json$Response(params: AssetsOrganDetailIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<OrganDetailDto>> {
    return assetsOrganDetailIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsOrganDetailIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganDetailIdGet$Json(params: AssetsOrganDetailIdGet$Json$Params, context?: HttpContext): Observable<OrganDetailDto> {
    return this.assetsOrganDetailIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrganDetailDto>): OrganDetailDto => r.body)
    );
  }

  /** Path part for operation `assetsOrganIconPathIdGet()` */
  static readonly AssetsOrganIconPathIdGetPath = '/assets/organ-icon-path/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsOrganIconPathIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganIconPathIdGet$Plain$Response(params: AssetsOrganIconPathIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<IconPathDto>> {
    return assetsOrganIconPathIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsOrganIconPathIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganIconPathIdGet$Plain(params: AssetsOrganIconPathIdGet$Plain$Params, context?: HttpContext): Observable<IconPathDto> {
    return this.assetsOrganIconPathIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<IconPathDto>): IconPathDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsOrganIconPathIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganIconPathIdGet$Json$Response(params: AssetsOrganIconPathIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<IconPathDto>> {
    return assetsOrganIconPathIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsOrganIconPathIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsOrganIconPathIdGet$Json(params: AssetsOrganIconPathIdGet$Json$Params, context?: HttpContext): Observable<IconPathDto> {
    return this.assetsOrganIconPathIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<IconPathDto>): IconPathDto => r.body)
    );
  }

  /** Path part for operation `assetsSampleImageSampleIdGet()` */
  static readonly AssetsSampleImageSampleIdGetPath = '/assets/sample-image/{sampleId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSampleImageSampleIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageSampleIdGet$Plain$Response(params: AssetsSampleImageSampleIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SampleImageDto>> {
    return assetsSampleImageSampleIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSampleImageSampleIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageSampleIdGet$Plain(params: AssetsSampleImageSampleIdGet$Plain$Params, context?: HttpContext): Observable<SampleImageDto> {
    return this.assetsSampleImageSampleIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<SampleImageDto>): SampleImageDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSampleImageSampleIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageSampleIdGet$Json$Response(params: AssetsSampleImageSampleIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SampleImageDto>> {
    return assetsSampleImageSampleIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSampleImageSampleIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageSampleIdGet$Json(params: AssetsSampleImageSampleIdGet$Json$Params, context?: HttpContext): Observable<SampleImageDto> {
    return this.assetsSampleImageSampleIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<SampleImageDto>): SampleImageDto => r.body)
    );
  }

  /** Path part for operation `assetsSampleImageSampleIdFavoritePost()` */
  static readonly AssetsSampleImageSampleIdFavoritePostPath = '/assets/sample-image/{sampleId}/favorite';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSampleImageSampleIdFavoritePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageSampleIdFavoritePost$Response(params: AssetsSampleImageSampleIdFavoritePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return assetsSampleImageSampleIdFavoritePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSampleImageSampleIdFavoritePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageSampleIdFavoritePost(params: AssetsSampleImageSampleIdFavoritePost$Params, context?: HttpContext): Observable<void> {
    return this.assetsSampleImageSampleIdFavoritePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `assetsSampleImageSampleIdFavoriteDelete()` */
  static readonly AssetsSampleImageSampleIdFavoriteDeletePath = '/assets/sample-image/{sampleId}/favorite';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSampleImageSampleIdFavoriteDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageSampleIdFavoriteDelete$Response(params: AssetsSampleImageSampleIdFavoriteDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return assetsSampleImageSampleIdFavoriteDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSampleImageSampleIdFavoriteDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageSampleIdFavoriteDelete(params: AssetsSampleImageSampleIdFavoriteDelete$Params, context?: HttpContext): Observable<void> {
    return this.assetsSampleImageSampleIdFavoriteDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `assetsSampleImageSampleIdNotePost()` */
  static readonly AssetsSampleImageSampleIdNotePostPath = '/assets/sample-image/{sampleId}/note';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSampleImageSampleIdNotePost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  assetsSampleImageSampleIdNotePost$Response(params: AssetsSampleImageSampleIdNotePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return assetsSampleImageSampleIdNotePost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSampleImageSampleIdNotePost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  assetsSampleImageSampleIdNotePost(params: AssetsSampleImageSampleIdNotePost$Params, context?: HttpContext): Observable<void> {
    return this.assetsSampleImageSampleIdNotePost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `assetsSampleImageMetadataSampleIdGet()` */
  static readonly AssetsSampleImageMetadataSampleIdGetPath = '/assets/sample-image/metadata/{sampleId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSampleImageMetadataSampleIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageMetadataSampleIdGet$Plain$Response(params: AssetsSampleImageMetadataSampleIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SampleImageMetadataDto>> {
    return assetsSampleImageMetadataSampleIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSampleImageMetadataSampleIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageMetadataSampleIdGet$Plain(params: AssetsSampleImageMetadataSampleIdGet$Plain$Params, context?: HttpContext): Observable<SampleImageMetadataDto> {
    return this.assetsSampleImageMetadataSampleIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<SampleImageMetadataDto>): SampleImageMetadataDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSampleImageMetadataSampleIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageMetadataSampleIdGet$Json$Response(params: AssetsSampleImageMetadataSampleIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SampleImageMetadataDto>> {
    return assetsSampleImageMetadataSampleIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSampleImageMetadataSampleIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageMetadataSampleIdGet$Json(params: AssetsSampleImageMetadataSampleIdGet$Json$Params, context?: HttpContext): Observable<SampleImageMetadataDto> {
    return this.assetsSampleImageMetadataSampleIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<SampleImageMetadataDto>): SampleImageMetadataDto => r.body)
    );
  }

  /** Path part for operation `assetsSampleImageAnnotationsIdGet()` */
  static readonly AssetsSampleImageAnnotationsIdGetPath = '/assets/sample-image-annotations/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSampleImageAnnotationsIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageAnnotationsIdGet$Plain$Response(params: AssetsSampleImageAnnotationsIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SampleImageAnnotationsListDto>> {
    return assetsSampleImageAnnotationsIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSampleImageAnnotationsIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageAnnotationsIdGet$Plain(params: AssetsSampleImageAnnotationsIdGet$Plain$Params, context?: HttpContext): Observable<SampleImageAnnotationsListDto> {
    return this.assetsSampleImageAnnotationsIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<SampleImageAnnotationsListDto>): SampleImageAnnotationsListDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsSampleImageAnnotationsIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageAnnotationsIdGet$Json$Response(params: AssetsSampleImageAnnotationsIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SampleImageAnnotationsListDto>> {
    return assetsSampleImageAnnotationsIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsSampleImageAnnotationsIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsSampleImageAnnotationsIdGet$Json(params: AssetsSampleImageAnnotationsIdGet$Json$Params, context?: HttpContext): Observable<SampleImageAnnotationsListDto> {
    return this.assetsSampleImageAnnotationsIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<SampleImageAnnotationsListDto>): SampleImageAnnotationsListDto => r.body)
    );
  }

  /** Path part for operation `assetsBodySystemListGet()` */
  static readonly AssetsBodySystemListGetPath = '/assets/body-system-list';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsBodySystemListGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemListGet$Plain$Response(params?: AssetsBodySystemListGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BodySystemListDto>> {
    return assetsBodySystemListGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsBodySystemListGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemListGet$Plain(params?: AssetsBodySystemListGet$Plain$Params, context?: HttpContext): Observable<BodySystemListDto> {
    return this.assetsBodySystemListGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<BodySystemListDto>): BodySystemListDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsBodySystemListGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemListGet$Json$Response(params?: AssetsBodySystemListGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BodySystemListDto>> {
    return assetsBodySystemListGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsBodySystemListGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemListGet$Json(params?: AssetsBodySystemListGet$Json$Params, context?: HttpContext): Observable<BodySystemListDto> {
    return this.assetsBodySystemListGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<BodySystemListDto>): BodySystemListDto => r.body)
    );
  }

  /** Path part for operation `assetsBodySystemDetailIdGet()` */
  static readonly AssetsBodySystemDetailIdGetPath = '/assets/body-system-detail/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsBodySystemDetailIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemDetailIdGet$Plain$Response(params: AssetsBodySystemDetailIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<BodySystemDetailDto>> {
    return assetsBodySystemDetailIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsBodySystemDetailIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemDetailIdGet$Plain(params: AssetsBodySystemDetailIdGet$Plain$Params, context?: HttpContext): Observable<BodySystemDetailDto> {
    return this.assetsBodySystemDetailIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<BodySystemDetailDto>): BodySystemDetailDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsBodySystemDetailIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemDetailIdGet$Json$Response(params: AssetsBodySystemDetailIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<BodySystemDetailDto>> {
    return assetsBodySystemDetailIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsBodySystemDetailIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemDetailIdGet$Json(params: AssetsBodySystemDetailIdGet$Json$Params, context?: HttpContext): Observable<BodySystemDetailDto> {
    return this.assetsBodySystemDetailIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<BodySystemDetailDto>): BodySystemDetailDto => r.body)
    );
  }

  /** Path part for operation `assetsBodySystemIconPathIdGet()` */
  static readonly AssetsBodySystemIconPathIdGetPath = '/assets/body-system-icon-path/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsBodySystemIconPathIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemIconPathIdGet$Plain$Response(params: AssetsBodySystemIconPathIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<IconPathDto>> {
    return assetsBodySystemIconPathIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsBodySystemIconPathIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemIconPathIdGet$Plain(params: AssetsBodySystemIconPathIdGet$Plain$Params, context?: HttpContext): Observable<IconPathDto> {
    return this.assetsBodySystemIconPathIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<IconPathDto>): IconPathDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assetsBodySystemIconPathIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemIconPathIdGet$Json$Response(params: AssetsBodySystemIconPathIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<IconPathDto>> {
    return assetsBodySystemIconPathIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assetsBodySystemIconPathIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assetsBodySystemIconPathIdGet$Json(params: AssetsBodySystemIconPathIdGet$Json$Params, context?: HttpContext): Observable<IconPathDto> {
    return this.assetsBodySystemIconPathIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<IconPathDto>): IconPathDto => r.body)
    );
  }

}
