/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { classworkDirectoriesStudyCategoryGet$Json } from '../fn/classwork/classwork-directories-study-category-get-json';
import { ClassworkDirectoriesStudyCategoryGet$Json$Params } from '../fn/classwork/classwork-directories-study-category-get-json';
import { classworkDirectoriesStudyCategoryGet$Plain } from '../fn/classwork/classwork-directories-study-category-get-plain';
import { ClassworkDirectoriesStudyCategoryGet$Plain$Params } from '../fn/classwork/classwork-directories-study-category-get-plain';
import { classworkDirectoriyIdDetailGet$Json } from '../fn/classwork/classwork-directoriy-id-detail-get-json';
import { ClassworkDirectoriyIdDetailGet$Json$Params } from '../fn/classwork/classwork-directoriy-id-detail-get-json';
import { classworkDirectoriyIdDetailGet$Plain } from '../fn/classwork/classwork-directoriy-id-detail-get-plain';
import { ClassworkDirectoriyIdDetailGet$Plain$Params } from '../fn/classwork/classwork-directoriy-id-detail-get-plain';
import { classworkDirectoryIdFilesGet$Json } from '../fn/classwork/classwork-directory-id-files-get-json';
import { ClassworkDirectoryIdFilesGet$Json$Params } from '../fn/classwork/classwork-directory-id-files-get-json';
import { classworkDirectoryIdFilesGet$Plain } from '../fn/classwork/classwork-directory-id-files-get-plain';
import { ClassworkDirectoryIdFilesGet$Plain$Params } from '../fn/classwork/classwork-directory-id-files-get-plain';
import { classworkDirectoryIdSampleImagesGet$Json } from '../fn/classwork/classwork-directory-id-sample-images-get-json';
import { ClassworkDirectoryIdSampleImagesGet$Json$Params } from '../fn/classwork/classwork-directory-id-sample-images-get-json';
import { classworkDirectoryIdSampleImagesGet$Plain } from '../fn/classwork/classwork-directory-id-sample-images-get-plain';
import { ClassworkDirectoryIdSampleImagesGet$Plain$Params } from '../fn/classwork/classwork-directory-id-sample-images-get-plain';
import { DirectoryDetailDto } from '../models/directory-detail-dto';
import { DirectoryTreeDto } from '../models/directory-tree-dto';
import { PdfFileDto } from '../models/pdf-file-dto';
import { SampleImageDiagnosisDto } from '../models/sample-image-diagnosis-dto';

@Injectable({ providedIn: 'root' })
export class ClassworkService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `classworkDirectoriesStudyCategoryGet()` */
  static readonly ClassworkDirectoriesStudyCategoryGetPath = '/classwork/directories/{studyCategory}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `classworkDirectoriesStudyCategoryGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoriesStudyCategoryGet$Plain$Response(params: ClassworkDirectoriesStudyCategoryGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DirectoryTreeDto>>> {
    return classworkDirectoriesStudyCategoryGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `classworkDirectoriesStudyCategoryGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoriesStudyCategoryGet$Plain(params: ClassworkDirectoriesStudyCategoryGet$Plain$Params, context?: HttpContext): Observable<Array<DirectoryTreeDto>> {
    return this.classworkDirectoriesStudyCategoryGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DirectoryTreeDto>>): Array<DirectoryTreeDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `classworkDirectoriesStudyCategoryGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoriesStudyCategoryGet$Json$Response(params: ClassworkDirectoriesStudyCategoryGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DirectoryTreeDto>>> {
    return classworkDirectoriesStudyCategoryGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `classworkDirectoriesStudyCategoryGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoriesStudyCategoryGet$Json(params: ClassworkDirectoriesStudyCategoryGet$Json$Params, context?: HttpContext): Observable<Array<DirectoryTreeDto>> {
    return this.classworkDirectoriesStudyCategoryGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DirectoryTreeDto>>): Array<DirectoryTreeDto> => r.body)
    );
  }

  /** Path part for operation `classworkDirectoriyIdDetailGet()` */
  static readonly ClassworkDirectoriyIdDetailGetPath = '/classwork/directoriy/{id}/detail';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `classworkDirectoriyIdDetailGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoriyIdDetailGet$Plain$Response(params: ClassworkDirectoriyIdDetailGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryDetailDto>> {
    return classworkDirectoriyIdDetailGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `classworkDirectoriyIdDetailGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoriyIdDetailGet$Plain(params: ClassworkDirectoriyIdDetailGet$Plain$Params, context?: HttpContext): Observable<DirectoryDetailDto> {
    return this.classworkDirectoriyIdDetailGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DirectoryDetailDto>): DirectoryDetailDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `classworkDirectoriyIdDetailGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoriyIdDetailGet$Json$Response(params: ClassworkDirectoriyIdDetailGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DirectoryDetailDto>> {
    return classworkDirectoriyIdDetailGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `classworkDirectoriyIdDetailGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoriyIdDetailGet$Json(params: ClassworkDirectoriyIdDetailGet$Json$Params, context?: HttpContext): Observable<DirectoryDetailDto> {
    return this.classworkDirectoriyIdDetailGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<DirectoryDetailDto>): DirectoryDetailDto => r.body)
    );
  }

  /** Path part for operation `classworkDirectoryIdSampleImagesGet()` */
  static readonly ClassworkDirectoryIdSampleImagesGetPath = '/classwork/directory/{id}/sample-images';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `classworkDirectoryIdSampleImagesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoryIdSampleImagesGet$Plain$Response(params: ClassworkDirectoryIdSampleImagesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageDiagnosisDto>>> {
    return classworkDirectoryIdSampleImagesGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `classworkDirectoryIdSampleImagesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoryIdSampleImagesGet$Plain(params: ClassworkDirectoryIdSampleImagesGet$Plain$Params, context?: HttpContext): Observable<Array<SampleImageDiagnosisDto>> {
    return this.classworkDirectoryIdSampleImagesGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SampleImageDiagnosisDto>>): Array<SampleImageDiagnosisDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `classworkDirectoryIdSampleImagesGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoryIdSampleImagesGet$Json$Response(params: ClassworkDirectoryIdSampleImagesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageDiagnosisDto>>> {
    return classworkDirectoryIdSampleImagesGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `classworkDirectoryIdSampleImagesGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoryIdSampleImagesGet$Json(params: ClassworkDirectoryIdSampleImagesGet$Json$Params, context?: HttpContext): Observable<Array<SampleImageDiagnosisDto>> {
    return this.classworkDirectoryIdSampleImagesGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SampleImageDiagnosisDto>>): Array<SampleImageDiagnosisDto> => r.body)
    );
  }

  /** Path part for operation `classworkDirectoryIdFilesGet()` */
  static readonly ClassworkDirectoryIdFilesGetPath = '/classwork/directory/{id}/files';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `classworkDirectoryIdFilesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoryIdFilesGet$Plain$Response(params: ClassworkDirectoryIdFilesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PdfFileDto>>> {
    return classworkDirectoryIdFilesGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `classworkDirectoryIdFilesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoryIdFilesGet$Plain(params: ClassworkDirectoryIdFilesGet$Plain$Params, context?: HttpContext): Observable<Array<PdfFileDto>> {
    return this.classworkDirectoryIdFilesGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PdfFileDto>>): Array<PdfFileDto> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `classworkDirectoryIdFilesGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoryIdFilesGet$Json$Response(params: ClassworkDirectoryIdFilesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PdfFileDto>>> {
    return classworkDirectoryIdFilesGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `classworkDirectoryIdFilesGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  classworkDirectoryIdFilesGet$Json(params: ClassworkDirectoryIdFilesGet$Json$Params, context?: HttpContext): Observable<Array<PdfFileDto>> {
    return this.classworkDirectoryIdFilesGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<PdfFileDto>>): Array<PdfFileDto> => r.body)
    );
  }

}
