/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SampleImageNoteRequest } from '../../models/sample-image-note-request';

export interface AssetsSampleImageSampleIdNotePost$Params {
  sampleId: number;
      body?: SampleImageNoteRequest
}

export function assetsSampleImageSampleIdNotePost(http: HttpClient, rootUrl: string, params: AssetsSampleImageSampleIdNotePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, assetsSampleImageSampleIdNotePost.PATH, 'post');
  if (params) {
    rb.path('sampleId', params.sampleId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

assetsSampleImageSampleIdNotePost.PATH = '/assets/sample-image/{sampleId}/note';
