/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SampleImageAnnotationsListDto } from '../../models/sample-image-annotations-list-dto';

export interface AssetsSampleImageAnnotationsIdGet$Json$Params {
  id: number;
}

export function assetsSampleImageAnnotationsIdGet$Json(http: HttpClient, rootUrl: string, params: AssetsSampleImageAnnotationsIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SampleImageAnnotationsListDto>> {
  const rb = new RequestBuilder(rootUrl, assetsSampleImageAnnotationsIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SampleImageAnnotationsListDto>;
    })
  );
}

assetsSampleImageAnnotationsIdGet$Json.PATH = '/assets/sample-image-annotations/{id}';
