/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SampleImageMetadataDto } from '../../models/sample-image-metadata-dto';

export interface AssetsSampleImageMetadataSampleIdGet$Plain$Params {
  sampleId: number;
}

export function assetsSampleImageMetadataSampleIdGet$Plain(http: HttpClient, rootUrl: string, params: AssetsSampleImageMetadataSampleIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SampleImageMetadataDto>> {
  const rb = new RequestBuilder(rootUrl, assetsSampleImageMetadataSampleIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('sampleId', params.sampleId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SampleImageMetadataDto>;
    })
  );
}

assetsSampleImageMetadataSampleIdGet$Plain.PATH = '/assets/sample-image/metadata/{sampleId}';
