/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SampleImageDiagnosisDto } from '../../models/sample-image-diagnosis-dto';

export interface ClassworkDirectoryIdSampleImagesGet$Plain$Params {
  id: number;
}

export function classworkDirectoryIdSampleImagesGet$Plain(http: HttpClient, rootUrl: string, params: ClassworkDirectoryIdSampleImagesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageDiagnosisDto>>> {
  const rb = new RequestBuilder(rootUrl, classworkDirectoryIdSampleImagesGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SampleImageDiagnosisDto>>;
    })
  );
}

classworkDirectoryIdSampleImagesGet$Plain.PATH = '/classwork/directory/{id}/sample-images';
