/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SampleImageMetadataDto } from '../models/sample-image-metadata-dto';
export interface ConversionJobDto {
  metadata?: SampleImageMetadataDto;
  sampleImageGroupId?: string | null;
  sampleImageID: number;
  sampleImageName?: string | null;
  sampleImagePath?: string | null;
  state?: string | null;
}
