/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Diagnosis } from '../models/diagnosis';
export interface DiangosesListDto {
  diagnoses: Array<Diagnosis>;
}
