/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PdfFile } from '../models/pdf-file';
import { SampleImage } from '../models/sample-image';
import { StudyCategory } from '../models/study-category';
export interface Directory {
  childDirectories?: Array<Directory>;
  description?: string | null;
  files?: Array<PdfFile>;
  id?: number;
  isPublic: boolean;
  keyWords?: string | null;
  name: string;
  nestingLevel: number;
  parent?: Directory;
  parentId?: number | null;
  path: string;
  sampleImages?: Array<SampleImage>;
  studyCategory: StudyCategory;
}
