/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DimensionPixel } from '../models/dimension-pixel';
export interface ImageSize {
  c?: number;
  height?: DimensionPixel;
  t?: number;
  width?: DimensionPixel;
  z?: number;
}
