/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModifyAction } from '../models/modify-action';
export interface ModifySampleImageRequest {
  action?: ModifyAction;
  iDs?: Array<number>;
}
