/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganDiagnosesDto } from '../models/organ-diagnoses-dto';
export interface OrgansListDto {
  organs: Array<OrganDiagnosesDto>;
}
