/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SampleImageAnnotationDto {
  boundingBox: string;
  description: string;
  id: number;
  name: string;
}
