/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OptimalDimension } from '../models/optimal-dimension';
export interface TileInfo {
  optimal?: OptimalDimension;
}
