/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateDirectoryInfoRequest {
  description?: string | null;
  keyWords?: string | null;
}
