/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SampleImageAdminDto } from '../../models/sample-image-admin-dto';

export interface AdminSampleImagesGet$Json$Params {
}

export function adminSampleImagesGet$Json(http: HttpClient, rootUrl: string, params?: AdminSampleImagesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SampleImageAdminDto>>> {
  const rb = new RequestBuilder(rootUrl, adminSampleImagesGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SampleImageAdminDto>>;
    })
  );
}

adminSampleImagesGet$Json.PATH = '/admin/sample-images';
